name: Execute Terragrunt Configuration
description: Action to execute terragrunt configuration

inputs:
  working_dir:
    description: terragrunt configuration releative path
    required: true
  deploy:
    description: apply terragrunt configuration
    required: true
    default: "false"
  ssh_private_key: 
    required: true

runs:
  using: composite
  steps:
    - name: test
      shell: bash
      run: |
        ls -al
        ls -al lifecycle
        ls -al ${{ inputs.working_dir }}

    - name: install ssh keys
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.ssh_private_key }}
        known_hosts: github.com

    - name: terragrunt-plan
      id: plan
      run: |
        terragrunt run-all plan \
          --terragrunt-include-external-dependencies \
          --terragrunt-source-update \
          --terragrunt-non-interactive \
          --terragrunt-working-dir ./${{ inputs.working_dir }}
      shell: bash
    - name: terragrunt-apply
      id: apply
      if: ${{ inputs.deploy == 'true' }}
      run: |
        terragrunt run-all apply \
          --terragrunt-include-external-dependencies \
          --terragrunt-source-update \
          --terragrunt-working-dir ${{ inputs.workding_dir }}
      shell: bash