name: Test outputs
on:
  workflow_dispatch
  
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "name=test::hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "name=test::world" >> $GITHUB_OUTPUT
    - name: Test Outputs
      run: echo ${{ steps.step1.outputs.test }} ${{ steps.step2.outputs.test }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
