name: Test outputs

on:
  workflow_dispatch:
    inputs:
      environment: 
        type: string
        default: ephem

    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENV_LONG: >
    ${{ fromJson('{\"dev\": \"development\",
    \"stage\": \"staging\",
    \"ephem\": \"ephemrical\",
    \"demo\": \"demo\",
    \"prod\": \"production\"}')[inputs.environment] }}


jobs:
  job1:
    runs-on: ubuntu-latest
    environment: stage
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: |
        echo "${{ env.ENV_LONG }}/Hello" >> $GITHUB_ENV
        echo "test=hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT
    - name: Test Outputs
      run: echo ${{ steps.step1.outputs.test }} ${{ steps.step2.outputs.test }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
