name: Terraform Plan

on:
  pull_request:
    paths:
      - 'sample-tf/**/*.tf'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: sample-tf
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform Plan
        working-directory: sample-tf
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform plan \
            -var="aws_access_key_id=${AWS_ACCESS_KEY_ID}" \
            -var="aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" \
            -out=tfplan.txt

      - name: Show Terraform Plan (to text)
        working-directory: sample-tf
        run: terraform show -no-color tfplan.txt > plan-output.txt

      - name: Upload plan-output.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-output
          path: sample-tf/plan-output.txt
