name: CI

on:
  workflow_dispatch:
    inputs:
      stack_to_deploy:
        type: boolean
        description: True or False
      Networking:
        type: boolean
        description: True or False
      ABC-Stack:
        type: boolean
        description: True or False                
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "boolean is ${{ github.event.inputs.stack_to_deploy }}" / ${{ inputs.stack_to_deploy }} 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
