name: test drop down

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
      metadata:
        type: boolean
        description: MetaStore
      datadog:
        type: boolean
        description: Datadog
      baseline:
        type: boolean
        description: Baseline
      networking:
        type: boolean
        description: Networking
      abc:
        type: boolean
        description: abc-stack
      datalake:
        type: boolean
        description: Datalake
      gw360:
        type: boolean
        description: GW360
      tableau:
        type: boolean
        description: tableau-server
      deploy:
        type: choice
        options:
        - plan
        - plan and apply
        default: plan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "boolean is ${{ github.event.inputs.stack_to_deploy }}" / ${{ inputs.stack_to_deploy }} 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
          echo "metadata is ${{ github.event.inputs.metadata }}" / ${{ inputs.metadata }}"
          echo "datadog is ${{ github.event.inputs.datadog }}" / ${{ inputs.datadog }}"
          echo "baseline is ${{ github.event.inputs.baseline }}" / ${{ inputs.baseline }}"
          echo "networking is ${{ github.event.inputs.networking }}" / ${{ inputs.networking }}"
          echo "abc is ${{ github.event.inputs.abc }}" / ${{ inputs.abc }}"
          echo "datalake is ${{ github.event.inputs.datalake }}" / ${{ inputs.datalake }}"
          echo "gw360 is ${{ github.event.inputs.gw360 }}" / ${{ inputs.gw360 }}"
          echo "tableau is ${{ github.event.inputs.tableau }}" / ${{ inputs.tableau }}"
          echo "deploy is ${{ github.event.inputs.deploy }}" / ${{ inputs.deploy }}


