name: Dynamic Matrix Example

on:
  workflow_dispatch:

env:
  PRIMARY_REGION: us-east-1
  SECONDARY_REGIONS: us-west-2,us-central-1

jobs:
  build:
    strategy:
      matrix:
        test: ${{ fromJSON(env.PRIMARY_REGION,env.SECONDARY_REGIONS) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Environment
        run: |
          echo "Environment: ${{ matrix.test }}"
        shell: bash

