name: Dynamic Matrix Example

on:
  workflow_dispatch:

env:
  PRIMARY_REGION: "us-east-1"
  SECONDARY_REGIONS: "us-west-2,us-central-1"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      regions: ${{ steps.set_env.outputs.regions }}
    steps:
      - name: Set Environment Variable
        id: set_env
        run: |
          echo "regions={\"regions\":[${{ env.PRIMARY_REGION }},${{ env.SECONDARY_REGIONS }}]}" >> $GITHUB_OUTPUT
          
      - name: test-outputs
        run: |
          echo ${{ steps.set_env.outputs.regions }}

  build:
    strategy:
      matrix: 
        regions: ${{ fromJSON(env.PRIMARY_REGION,env.SECONDARY_REGIONS) }}
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Environment
        run: |
          echo "Environment: ${{ matrix.regions }}"
        shell: bash

