name: Dynamic Matrix Example

on:
  workflow_dispatch:

env:
  PRIMARY_REGION: us-east-1
  SECONDARY_REGIONS: us-west-2,us-central-1

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      regions: ${{ set_env.outputs.regions }}
    steps:
      - name: Set Environment Variable
        id: set_env
        run: |
          echo "regions=[${{ env.PRIMARY_REGIONS }} + ${{ env.SECONDARY_REGIONS }} ]

  build:
    strategy:
      matrix:
        test: ${{ fromJSON(needs.setup.outputs.regions) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Environment
        run: |
          echo "Environment: ${{ matrix.test }}"
        shell: bash

