name: Dynamic Matrix Example

on:
  workflow_dispatch:
    inputs:
      primary:
        description: 'Primary Region'
        required: true
        default: 'us-east-1'
      secondary:
        description: 'Secondary Regions'
        required: true
        default: 'us-west-2,us-central-1'
        
env:
  primary: "us-east-1"
  secondary: "us-west-2,us-central-1"

jobs:
  build:
    strategy:
      matrix:
        environment: ${{ fromJson(env.primary + ',' + env.secondary) }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Environment
        run: echo "Environment: ${{ matrix.environment }}"

