name: Dynamic Matrix Example

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu'
        options: 
          - name: 'Ubuntu'
            value: 'ubuntu'
          - name: 'Linux'
            value: 'linux'
          - name: 'RHEL'
            value: 'rhel'
      node_version:
        description: 'Node.js Version'
        required: true
        default: '12'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [${{ github.event.inputs.node_version }}]
        os: ${{ fromJson(github.event.inputs.os) }}

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Checkout code
        uses: actions/checkout@v2

      # Rest of the steps...

      - name: check inputs
        run: |
          echo ${{ matrix.node_version }} 
          echo ${{ matrix.os }}
