name: Dynamic Matrix Example

on:
  workflow_dispatch:

env:
  PRIMARY_REGION: "us-east-1"
  SECONDARY_REGIONS: "us-west-2,us-central-1"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      regions: ${{ toJSON(steps.set_env.outputs.regions) }}
    steps:
      - name: Set Environment Variable
        id: set_env
        run: |
          echo "regions=[${{env.PRIMARY_REGION}},${{env.SECONDARY_REGIONS}}]" >> $GITHUB_OUTPUT
          
      - name: test-outputs
        run: |
          echo ${{ steps.set_env.outputs.regions }}

  build:
    strategy:
      matrix: 
        regions: [us-east-1,us-west-2]
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Environment
        run: |
          echo "Environment: ${{ matrix.regions }}"
        shell: bash

