name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      # name:
      #   type: choice
      #   description: Who to greet
      #   options: 
      #   - monalisa
      #   - cschleiden
      message:
        # required: true
        type: string
      # use-emoji:
      #   type: boolean
      #   description: Include  emojis
      environment:
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: test withouth enviornment
      run: |
        echo ${{ secrets.test }}
        
  greet:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
      
    - name: Test environment secrets
      run: |
        echo ${{ secrets.test }}
        exit 1
        
    - name: create-github-issue
      id: create-issue
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ env.GITHUB_TOKEN }}
        title: test
        body: |
          # Context

          [Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})

          ```
          REF         : ${{ github.ref }}
          SHA         : ${{ github.sha }}
          REPO        : ${{ github.repository }}
          RUN_ID      : ${{ github.run_id }}
          RUN_NUMBER  : ${{ github.run_number}} 
          RUN_ATTEMPT : ${{ github.run_attempt }}
          ACTOR       : ${{ github.actor }}
          WORKFLOW    : ${{ github.workflow }}
          EVENT       : ${{ github.event_name }}
          ```
        labels: release
        
        
