name: Trigger environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      region:
        type: choice
        description: Select region
        options:
        - us-east-1
        - us-west-1
      deploy:
        type: choice
        description: 'Terragrunt plan and(or) apply'
        default: 'plan'
        options:
        - plan
        - apply


permissions:
  contents: read
  id-token: write


env:
  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  ENV: ${{ inputs.environment }}
  AWS_DEFAULT_REGION: ${{ inputs.region }}
  GITHUB_OAUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


jobs:    
  prod:
    name: 'deploy-prod-environment'
    uses: ./.github/workflows/stack-workflow.yml
    with: 
      region: ${{ inputs.region }}
      environment: 'prod'
      deploy: false
    secrets: inherit    