name: Create Release
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3.1.0
      
      - name: create-release
        uses: release-drafter/release-drafter@v5.20.0
        with:
          publish: true
          prerelease: false
          # config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
