name: Test-jobs-strategy-call-workflow
on: 
  workflow_call:
    inputs:
      dr_enabled:
        type: boolean
      region:
        type: string


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo ${{ inputs.dr_enabled }}
          echo ${{ inputs.region }}
        shell: bash 
        
      - name: TF config for us-west-2 and dr
        if: ${{ inputs.dr_enabled && inputs.region == 'us-west-2' }}
        run: |
          echo "TF_BACKEND_CONFIG=key=gw360/ephemrical/infra/ephem/api/us-west-2/terraform.tfstate" >> $GITHUB_ENV
          echo "TF_CLI_ARGS=-target=module.api.module.ecs_service" >> $GITHUB_ENV
        shell: bash
        
      - name: Step 1
        run: echo "This is job2"
        
      - name: printenv
        run: printenv
        
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is job3"



