name: ContinuousIntegration

on:
  pull_request:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test-folder:
      runs-on: ubuntu-latest
      outputs:
        changed_files: ${{ github.changed-files.outputs.all_changed_files }}
      steps:
        - name: checkout
          uses: actions/checkout@v3
        
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v35
          
        - name: print outputs
          run: |
            echo ${{ toJson(steps.changed-files.outputs.all_changed_files) }}
            
            
  new-job:
    runs-on: ubuntu-latest
    needs: test-folder
    steps:
      - run: |
          echo ${{ needs.test-folder.outputs.changed_files }}
