# .github/workflows/issue-on-push.yml
on: [push]
name: Create an issue on push
permissions:
  contents: read
  issues: write 
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: install-tfcmt
        run: |
          version=$(curl -LsS https://api.github.com/repos/suzuki-shunsuke/tfcmt/releases/latest | jq -r .name)
          curl -LsS https://github.com/suzuki-shunsuke/tfcmt/releases/download/${version}/tfcmt_linux_amd64.tar.gz -o /tmp/tfcmt_linux_amd64.tar.gz
          tar -xvzf /tmp/tfcmt_linux_amd64.tar.gz
          mv tfcmt /usr/local/bin/tfcmt
          chmod +x /usr/local/bin/tfcmt
        shell: bash

      - name: run tfcmt
        run: |
          cd sample-tf
          terraform init
          tfcmt -repo tfcmt -pr ${{ steps.create-issue.outputs.number }} plan -- terraform plan