name: test create-issue workflow

on:
  workflow_call:
    inputs:
      issue_number:
        description: Github Issue/PR Number
        type: string
        default: 0
        
jobs:
  test-value:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          echo ${{ inputs.issue_number }}
