name: Test Backend

on: 
  pull_request:
    branch:
    - "development"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment to run.
        default: ephem
        options:
        - dev
        - stage
        - ephem
        - demo
        - prod
      

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENV_SHORT: ${{ github.event.inputs.environment }}
  ENV_LONG: >
    ${{ fromJson('{ 
    "dev": "development", 
    "stage": "staging", 
    "ephem": "ephermical", 
    "demo": "demo", 
    "prod": "production"}')[github.event.inputs.environment] }}

permissions:
  id-token: write
  contents: read
  
jobs:
  set-state:
    name: set backend
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3 
    
      - name: set backend
        shell: bash
        run: |
          cd infra/bg-init
          cat backend.tf
          ENV_LONG=${{ env.ENV_LONG }}
          ENV_SHORT=${{ env.ENV_SHORT }}
          sed -i "s/{ENV1}/$ENV_LONG/g;s/{ENV2}/$ENV_SHORT/g" backend.tf > backend.tf
          cat backend.tf      
